service: test-cognito-integration

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: ap-southeast-1

  environment:
    ping: pong

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'cognito:*'
      Resource:
        - '*'

plugins:
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

package:
  excludeDevDependencies: false
  individually: true

functions:
  ping:
    handler: src/handlers/ping.handler
    events:
      - http:
          path: ping
          method: get

  register-user:
    handler: src/handlers/register-user.handler
    events:
      - http:
          path: users/register
          method: post

  confirm-user:
    handler: src/handlers/confirm-registration.handler
    events:
      - http:
          path: users/confirm
          method: post

  resend-confirmation-request:
    handler: src/handlers/resend-confirmation-code.handler
    events:
      - http:
          path: users/resend-confirmation
          method: post
